#!/bin/bash

# This script used to use /etc/rc.local for scheduling Sever mode nonpersistence switching to Classic mode
# It is no longer used and is left here for compatibility purposes only
# Server mode nonpersistence is now fully handled by wlanpi-server-nonpersistence.service